data:
  predict: data/predict/predict.csv
  raw: data/raw/Students_Grading_Dataset.csv
  interim: data/interim
  processed: data/processed/final
  full: data/full
  predict_output: data/processed/predict
  logging: data/logs

model:
  score_cluster: models/score_cluster_model
  background_cluster: models/background_cluster_model
  mental_cluster: models/mental_cluster_model

testing:
  score_cluster: testing/models/score_cluster_model
  background_cluster: testing/models/background_cluster_model
  mental_cluster: testing/models/mental_cluster_model
  full: testing/data/full