from config.enum_headers import RenamedColumns, CandidateColumns, RawColumns

RAW_TO_INTERM_MAP = {
    RawColumns.Student_ID: RenamedColumns.student_id,
    RawColumns.First_Name: RenamedColumns.first_name,
    RawColumns.Last_Name: RenamedColumns.last_name,
    RawColumns.Email: RenamedColumns.email,
    RawColumns.Gender: RenamedColumns.gender,
    RawColumns.Age: RenamedColumns.age,
    RawColumns.Department: RenamedColumns.department,
    RawColumns.Attendance_Percent: RenamedColumns.attendance_percent,
    RawColumns.Midterm_Score: RenamedColumns.midterm_score,
    RawColumns.Final_Score: RenamedColumns.final_score,
    RawColumns.Assignments_Avg: RenamedColumns.assignments_avg,
    RawColumns.Quizzes_Avg: RenamedColumns.quizzes_avg,
    RawColumns.Participation_Score: RenamedColumns.participation_score,
    RawColumns.Projects_Score: RenamedColumns.projects_score,
    RawColumns.Total_Score: RenamedColumns.total_score,
    RawColumns.Grade: RenamedColumns.grade,
    RawColumns.Study_Hours_per_Week: RenamedColumns.study_hours_per_week,
    RawColumns.Extracurricular_Activities: RenamedColumns.extracurricular_activities,
    RawColumns.Internet_Access_at_Home: RenamedColumns.internet_access_at_home,
    RawColumns.Parent_Education_Level: RenamedColumns.parent_education_level,
    RawColumns.Family_Income_Level: RenamedColumns.family_income_level,
    RawColumns.Stress_Level: RenamedColumns.stress_level,
    RawColumns.Sleep_Hours_per_Night: RenamedColumns.sleep_hours_per_night,
}

RENAMED_TO_CANDIDATE_MAP = {
    RenamedColumns.student_id: CandidateColumns.student_id,
    RenamedColumns.age: CandidateColumns.age,
    RenamedColumns.attendance_percent: CandidateColumns.attendance_percent,
    RenamedColumns.midterm_score: CandidateColumns.midterm_score,
    RenamedColumns.final_score: CandidateColumns.final_score,
    RenamedColumns.assignments_avg: CandidateColumns.assignments_avg,
    RenamedColumns.quizzes_avg: CandidateColumns.quizzes_avg,
    RenamedColumns.participation_score: CandidateColumns.participation_score,
    RenamedColumns.projects_score: CandidateColumns.projects_score,
    RenamedColumns.total_score: CandidateColumns.total_score,
    RenamedColumns.study_hours_per_week: CandidateColumns.study_hours_per_week,
    RenamedColumns.extracurricular_activities: CandidateColumns.b_extracurricular_activities,
    RenamedColumns.internet_access_at_home: CandidateColumns.b_internet_access_at_home,
    RenamedColumns.sleep_hours_per_night: CandidateColumns.sleep_hours_per_night,
}
